config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :index, :create, :show, :edit, :update, :destroy]
  get '/users/hub/:id', to: 'users#hub', as: :hub
  get '/users/welcome', to: 'users#welcome', as: :welcome #needs fix, routes to show

  resources :friendships, only: [:create, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :quiz_responses, only: [:new, :create, :show]
  resources :congress_members, only: [:index, :show]
  resources :entries, only: [:new, :create, :edit, :update, :destroy]
  resources :comments, only: [:new, :create, :edit, :update, :destroy]

  root 'users#new'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @entry = Entry.find(params[:format])
    render 'comments/new'
  end

  def create
    comment = Comment.new
    comment.commentable_id = params[:commentable_id]
    comment.commentable_type = params[:commentable_type]
    comment.body = params[:body]
    comment.user_id = current_user.id
    if comment.body == ""
      flash[:error] = "Comment body must not be blank."
      redirect_to controller: 'comments', action: 'new', format: params[:commentable_id]
    else
      if comment.save
        flash[:notice] = "Your comment was saved!"
        redirect_to controller: 'users', action: 'show', id: params[:entry_user_id]
      else
        flash[:error] = comment.errors.full_messages[0]
        redirect_to controller: 'comments', action: 'new', format: params[:commentable_id]
      end
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @entry = Entry.find(@comment.commentable_id)
    render 'comments/edit'
  end

  def update
    comment = Comment.find(params[:id])
    comment.body = params[:body]
    if comment.save
      redirect_to controller: 'users', action: 'show', id: params[:entry_user_id]
    else
      flash[:error] = comment.errors.full_messages[0]
      redirect_to controller: 'comments', action: 'edit', comment: comment.id
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to controller: 'users', action: 'show', id: params[:entry_user]
  end

end

app/views/comments/edit.html.erb
<div class="usa-grid profile-comment-form-cont">
  <%= flash[:notice] %>
  <%= flash[:error] %>
  <%= form_tag comment_path, method: :put do %>
    Comment: <%= text_area_tag :body, @comment.body %>
    <%= hidden_field_tag :entry_user_id, @entry.user_id %>
    <%= submit_tag "Update" %>
  <% end %>
</div>

app/views/comments/new.html.erb
<div class="usa-grid profile-comment-form-cont">
  <%= flash[:notice] %>
  <%= flash[:error] %>
  <%= form_tag comments_path, method: :post do %>
    Comment: <%= text_area_tag :body %>
    <%= hidden_field_tag :entry_user_id, @entry.user_id %>
    <%= hidden_field_tag :commentable_id, @entry.id %>
    <%= hidden_field_tag :commentable_type, @entry.class %>
    <%= submit_tag "Submit" %>
  <% end %>
</div>