config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :index, :create, :show, :edit, :update, :destroy]
  get '/users/hub/:id', to: 'users#hub', as: :hub
  get '/users/welcome', to: 'users#welcome', as: :welcome #needs fix, routes to show

  resources :friendships, only: [:create, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :quiz_responses, only: [:new, :create, :show]
  resources :congress_members, only: [:index, :show]
  resources :entries, only: [:new, :create, :edit, :update, :destroy]
  resources :comments, only: [:new, :create, :edit, :update, :destroy]

  root 'users#new'
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def new
    respond_to do |format|
      format.html #still need to test graceful degradation
      format.js
    end
  end

  def create
    @entry = Entry.new
    @entry.user_id = current_user.id
    @entry.title = params[:title]
    @entry.body = params[:body]
    @entry.entry_type = params[:entry_type]
    if @entry.body == ""
      flash[:error] = "Post body must not be blank."
    else
      if @entry.save
        flash[:notice] = "Your post was saved!"
      else
        flash[:error] = @entry.errors.full_messages
      end
    end
    @user = current_user
    respond_to do |format|
      format.html { redirect_to controller: 'users', action: 'show', id: current_user.id }
      format.js
    end
  end

  def edit
    @post = Entry.find(params[:post])
    render 'entries/edit'
  end

  def update
    entry = Entry.find(params[:id])
    entry.title = params[:title]
    entry.body = params[:body]
    if entry.save
      redirect_to controller: 'users', action: 'show', id: current_user.id
    else
      flash[:error] = entry.errors.full_messages
      redirect_to controller: 'entries', action: 'edit', post: entry.id
    end
  end

  def destroy
    entry = Entry.find(params[:id])
    entry.destroy
    redirect_to controller: 'users', action: 'show', id: current_user.id
  end

end

app/views/entries/_edit.html.erb
<div class="usa-grid profile-post-edit-form-cont">
  <%= flash[:notice] %>
  <%= flash[:error] %>
  <%= form_tag entry_path, method: :put do %>
    Title(optional): <%= text_field_tag :title, @post.title %><br>
    Body: <%= text_area_tag :body, @post.body %>
    <%= submit_tag "Update" %>
  <% end %>
</div>

app/views/entries/_profile_post_form.html.erb
  <%= flash[:error] %>
  <%= form_tag '/entries', remote: true do %>
    Title(optional): <%= text_field_tag :title %><br>
    Body: <%= text_area_tag :body %>
    <%= hidden_field_tag :entry_type, "profile_post" %>
    <%= submit_tag "Submit", class: "usa-button-secondary"%>
  <% end %>

app/views/entries/_show.html.erb
<div class="profile-post-cont">
  <%= image_tag @user.avatar.url(:thumb), class: "profile-post-avatar" %>
  <!-- consider adding user name with poster photo but for now seems redundant -->
  <% if signed_in? && @user.id == current_user.id %>
  <div class="profile-post-edit-cont">
    <%= link_to "Edit", edit_entry_path(post.id, post: post) %> |
    <!-- confirm isn't currently working but this should be handled with ajax -->
    <%= link_to "Delete", post, method: :delete, confirm: "Are you sure you want to delete this post?" %>
  </div>
  <% end %>
  <div class="profile-post-content">
    <p><%= post.title %></p>
    <hr>
    <p><%= post.body %></p>
    <p><%= post.created_at.strftime('%l:%M%P - %m/%d/%y') %></p>
  </div>
  <% if signed_in? %>
    <%= button_to "Comment", new_comment_path(post.id), method: :get, class: "usa-button-primary-alt" %>
  <% end %>
  <% post.comments.reverse.each do |comment| %>
    <div class="usa-grid profile-post-comment-cont">
      <% commenter = User.find(comment.user_id) %>
      <%= link_to user_path(commenter.id) do %>
         <%= image_tag commenter.avatar.url(:thumb), class: "comment-user-avatar" %>
      <% end %>
      <div class="comment-body-cont">
        <%= link_to commenter.username, "/users/#{commenter.id}" %><br>
        <hr>
        <%= comment.body %><br><br>
        <%= comment.created_at.strftime('%l:%M%P - %m/%d/%y') %>
        <% if signed_in? && comment.user.id == current_user.id %>
        | <%= link_to "Edit", edit_comment_path(comment.id, comment: comment) %> |
          <!-- confirm isn't currently working but this shoule handled with ajax -->
          <%= link_to "Delete", comment_path(id: comment.id, entry_user: post.user_id), method: :delete, confirm: "Are you sure you want to delete this comment?" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/entries/create.js.erb
$('#profile-post-form-cont').slideUp('slow');
$('#new-post-btn').fadeIn();
$('#profile-posts-cont').prepend('<%= j render "/entries/show", post: @entry %>').hide().fadeIn(800);

app/views/entries/edit.html.erb
<div class="usa-grid profile-post-edit-form-cont">
  <%= flash[:notice] %>
  <%= flash[:error] %>
  <%= form_tag entry_path, method: :put do %>
    Title(optional): <%= text_field_tag :title, @post.title %><br>
    Body: <%= text_area_tag :body, @post.body %>
    <%= submit_tag "Update" %>
  <% end %>
</div>

app/views/entries/new.html.erb
<div style="margin-top: 130px">
  <%= render "_profile_post_form" %>
</div>

app/views/entries/new.js.erb
$('#new-post-btn').hide();
$('#profile-post-form-cont').css("display", "block").hide().slideDown().fadeIn(800);