config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :index, :create, :show, :edit, :update, :destroy]
  get '/users/hub/:id', to: 'users#hub', as: :hub
  get '/users/welcome', to: 'users#welcome', as: :welcome #needs fix, routes to show

  resources :friendships, only: [:create, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :quiz_responses, only: [:new, :create, :show]
  resources :congress_members, only: [:index, :show]
  resources :entries, only: [:new, :create, :edit, :update, :destroy]
  resources :comments, only: [:new, :create, :edit, :update, :destroy]

  root 'users#new'
end

app/models/user.rb
# require 'bcrypt'

class User < ApplicationRecord
  has_secure_password

  has_many :friendships
  has_many :entries
  has_many :responses
  has_many :quizzes, through: :responses, source: :quiz_id

  # paperclip association and validation from docs
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", mini: "50x50>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  # validates :password, :length => { :minimum => 5 }
  # validates_confirmation_of :password
  validates_presence_of :username, :email #, :password_hash
  validates_uniqueness_of :username, :email

  # include BCrypt
  #
  # def password
  #   @password ||= Password.new(password_hash)
  # end
  #
  # def password=(new_password)
  #   @password = Password.create(new_password)
  #   self.password_hash = @password
  # end
  #
  # def self.authenticate(username, password)
  #   @user = User.find_by(username: username)
  #   if @user && @user.password == password
  #     @user
  #   else
  #     nil
  #   end
  # end

end

app/controllers/users_controller.rb
require 'uri'
require 'net/http'
require 'openssl'

class UsersController < ApplicationController

  def welcome
    render 'users/welcome'
  end

  def index
    @query = params[:q]
    @query_array = @query.split(' ')
    # consider refactor to hash avoiding the nested loop and minimize repitition
    # this solution also lead's to possible duplicates as the search term will insert the record twice if say "elizabeth" and "warren" are found separetly
    if @query_array.count > 1
      @congress_members = []
      @users = []
      @query_array.each do |term|
        @users += User.search(username_cont: term).result
        @members_raw = CongressMember.search(f_name_or_l_name_cont: term).result
        @members_raw.each do |member|
          @congress_members << ProPublicaCongressAdapter.new(endpoint: "find_member", member_id: member.politician_id).single_member_details
        end
      end
    else
      @users = User.search(username_cont: @query).result
      @members_raw = CongressMember.search(f_name_or_l_name_cont: @query).result
      @congress_members = []
      @members_raw.each do |member|
        @congress_members << ProPublicaCongressAdapter.new(endpoint: "find_member", member_id: member.politician_id).single_member_details
      end
    end

    render 'users/search_results'
  end

  def new
  end

  def create
    user = User.new(user_params)
    user.avatar = "https://github.com/DigiCiti/DigitalCitizen/blob/development/app/assets/images/default_avatar.png?raw=true"
    # consider having sample friendships with different status
    # sample entry and comment which each explain their process
    if user.save
      session[:user_id] = user.id

      friendship = Friendship.create(user_id: 16, friended_user: current_user.id, status: "approved")
      friend_req_sent = Friendship.create(user_id: current_user.id, friended_user: 15)
      friend_req_recieved = Friendship.create(user_id: 14, friended_user: current_user.id)

      entry = Entry.new
      entry.user_id = current_user.id
      entry.title = "A Sample Post on Your Profile"
      entry.body = "Use your profile posts to communicate things to peers on your network who will see them in their hub feed. Only you make posts on your page but other users can comment depending on permissions you've given."
      entry.entry_type = "profile_post"
      entry.save

      comment = Comment.new
      comment.commentable_id = entry.id
      comment.commentable_type = "Entry"
      comment.body = "This is a sample comment for a sample post you would have made. People can comment on your posts."
      comment.user_id = 16
      comment.save

      redirect_to "/users/#{user.id}/edit", flash: { notice: "You can edit later and choose \"hub\" or \"profile\" to get going." }
    else
      redirect_to '/', flash: { error: user.errors.full_messages }
    end
  end

  def hub
    @user = current_user

    @friendships = Friendship.where("(user_id = '#{@user.id}'
      or friended_user = '#{@user.id}')
      and status = 'approved'")
    @pending_friendship_requests = Friendship.where("friended_user = '#{@user.id}'
      and status = 'unanswered'")
    @sent_pend_friend_req = Friendship.where("user_id = '#{@user.id}'
      and status = 'unanswered'")

    @feed_friend_posts = []
    @friendships.each do |friend|
      @feed_friend_posts << User.find(friend.user_id).entries.last
    end

    # members are not currently sorted by alpha order beyond their last initial
    @house_members = ProPublicaCongressAdapter.new(endpoint: "member_list", branch: "house")
    @house_members = @house_members.members_basic_details
    @senate_members = ProPublicaCongressAdapter.new(endpoint: "member_list", branch: "senate")
    @senate_members = @senate_members.members_basic_details

    render 'users/hub'
  end

  def show
    @user = User.find(params[:id])
    @posts = Entry.where("user_id = '#{@user.id}' and entry_type = 'profile_post'").last(10)
    # need to setup offset for pagination or additional posts to load on scroll
    @posts = @posts.sort_by &:created_at
    @posts = @posts.reverse
    # started to work through avoidance of User.find call in view but not sure if
    # it would even be less expensive...
    # p '*' * 100
    # @comments = []
    # @posts.each do |post|
    #   @comments = post.comments
    # end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    user = User.find(current_user.id)
    if params[:user][:avatar] != nil
      user.avatar = params[:user][:avatar]
    end
    user.f_name = params[:user][:f_name]
    user.l_name = params[:user][:l_name]
    user.city = params[:user][:city]
    user.state = params[:user][:state]
    user.country = params[:user][:country]
    user.ideology = params[:user][:ideology]
    user.party = params[:user][:party]
    if user.save
      redirect_to controller: 'users', action: 'show', id: current_user.id
    else
      redirect_to "/users/#{user.id}/edit", flash: { error: user.errors.full_messages }
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
  end

end

app/views/users/_friend_display.erb
<% if friendship.user_id == @user.id %>
  <% @contact_id = friendship.friended_user %>
<% else %>
  <% @contact_id = friendship.user_id %>
<% end %>
<% contact = User.find(@contact_id) %>
<%= image_tag contact.avatar.url(:mini), class: "hub-user-avatar-mini" %>
<%= link_to(contact.username, user_path(@contact_id)) %>

app/views/users/edit.html.erb
<div class="usa-grid usa-width-one-half" id="profile-page-main-cont">
  <!-- put the flash up on a proper condition and clean it up in a div with style -->
  <%= flash[:notice] %>
  <div id="profile-info-cont">
    <div>
      <span class="profile-username-header">Edit Your Profile</span>
      <p>Choose your profile image:</p>
      <%= image_tag @user.avatar.url(:medium), id: "profile-photo-cont" %>
      <% if signed_in? && @user.id == current_user.id %>
        <%= form_for @user, url: user_path(current_user.id), html: { multipart: true } do |f| %>
          <%= f.file_field :avatar %><br>
          First Name: <%= f.text_field :f_name, class: 'auth-inputs' %><br>
          Last Name: <%= f.text_field :l_name, class: 'auth-inputs' %><br>
          City: <%= f.text_field :city, class: 'auth-inputs' %><br>
          State: <%= f.text_field :state, class: 'auth-inputs' %><br>
          Country: <%= f.text_field :country, class: 'auth-inputs' %><br>
          Ideology: <%= f.text_field :ideology, class: 'auth-inputs' %><br>
          Party Affiliation: <%= f.text_field :party, class: 'auth-inputs' %><br>
          Privacy Options: <%= f.text_field :privacy_setting, class: 'auth-inputs' %><br>
          <%= f.submit "Save" %>
        <% end %>
      <% end %>
    </div>
    <% if signed_in? && @user.id != current_user.id && !friend?(@user.id) %>
    <%= button_to "Add Contact", friendships_path(add_id: @user.id), method: :post %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% end %>
  </div>

</div>

app/views/users/hub.html.erb
<div class="usa-grid usa-width-one-half" id="hub-container">
  <h1 class="usa-header"><%= current_user.username %>'s Hub</h1>
  <p>This project is in very early stages of development so there aren't many features yet.  This page will eventually serve as a central place for a user to manage their activities on the site.</p>
  <p>Each of the sections below is a temporary placeholder for a feature of the hub page.  Some of them are semi-functional while others are merely just a note.</p>
  <p>Please take a moment to explore them.</p>
</div>

<div class="usa-grid usa-width-one-third hub-section">
  <h5>Connections</h5>
  <hr>
  <div class="hub-friend-sub-sec">
    <p>Contact List:</p>
    <% @friendships.each do |friendship| %>
    <p><%= render partial: "friend_display", locals: {friendship: friendship} %></p>
    <% end %>
  </div>

  <div class="hub-friend-sub-sec">
    <p>Received Requests:</p>
    <p class="notice"><%= notice %></p>
    <% @pending_friendship_requests.each do |friendship| %>
    <p><%= render partial: "friend_display", locals: {friendship: friendship} %>
      - <%= link_to "Approve", friendship_path(friendship.id, status: "approved"), method: :put %>
      | <%= link_to "Reject", friendship_path(friendship.id, status: "rejected"), method: :put %>
    </p>
    <% end %>
  </div>

  <div class="hub-friend-sub-sec">
    <p>Sent Requests</p>
    <% @sent_pend_friend_req.each do |friendship| %>
      <p><%= render partial: "friend_display", locals: {friendship: friendship} %></p>
    <% end %>
  </div>
</div>

<div class="usa-grid usa-width-one-third hub-section">
  <h5>Your Political Identity</h5>
  <hr>
  <p>Take a quiz to determine your political stance:</p>
  <%= link_to "Take Quiz", '/quiz_responses/new' %>

  <p>Your past quiz results:</p>
  <% count = 0 %>
  <% @user.responses.each do |response| %>
    <% count += 1 %>
    <p>Quiz <%= count %> had a result of: "<%= response.quiz_result %>"</p>
  <% end %>
  <% if count == 0 %>
    <p>Complete the quiz at least once to see results.</p>
  <% end %>
</div>

<div class="usa-grid usa-width-one-third hub-section">
  <p>Connect with Congress</p>
  <div class="hub-c-member-sub-sec">
    <p>Senate</p>
    <p>Name(sorted by last) - State - Party - %Voting with Party</p>
    <% @senate_members.each do |member| %>
      <div class="hub-c-member-details-cont">
        <%= image_tag "https://theunitedstates.io/images/congress/225x275/#{member[:id]}.jpg", alt: "#{member[:full_name]} Image", class: "hub-c-member-img" %>
        <p><%= link_to "#{member[:full_name]}", congress_member_path(member_id: member[:id]) %>
          - <%= "#{member[:state]} - #{member[:party]} -
          #{member[:votes_with_party_pct]}" %>
        </p>
      </div>
    <% end %>
  </div>
  <div class="hub-c-member-sub-sec">
    <p>House</p>
    <p>Name(sorted by last) - State - Party - %Voting with Party</p>
    <% @house_members.each do |member| %>
      <div class="hub-c-member-details-cont">
        <%= image_tag "https://theunitedstates.io/images/congress/225x275/#{member[:id]}.jpg", alt: "#{member[:full_name]} Image", class: "hub-c-member-img" %>
        <p><%= link_to "#{member[:full_name]}", congress_member_path(member_id: member[:id]) %>
          - <%= "#{member[:state]} - #{member[:party]} -
          #{member[:votes_with_party_pct]}" %>
        </p>
      </div>
    <% end %>
  </div>
</div>

<div class="usa-grid usa-width-one-third hub-section">
  <p>Post</p>
  <p>Feed</p>
  <% @feed_friend_posts.each do |post| %>
    <p><%= User.find(post.user_id).username %></p>
    <p><%= post.title %></p>
    <p><%= post.body %></p>
    <p><%= post.updated_at %></p>
  <% end %>
</div>

<div class="usa-grid usa-width-one-third hub-section">
  <p>Debate</p>
</div>

<div class="usa-grid usa-width-one-third hub-section">
  <p>Game</p>
</div>

<div class="usa-grid usa-width-one-third hub-section">
  <p>Events</p>
</div>

<div class="usa-grid usa-width-one-third hub-section">
  <p>Legislation</p>
</div>

<div class="usa-grid usa-width-one-third hub-section">
  <p>News</p>
</div>

<div class="usa-grid usa-width-one-third hub-section">
  <p>Wiki</p>
</div>

<div class="usa-grid usa-width-one-third hub-section">
  <p>Academia</p>
</div>

<div class="usa-grid usa-width-one-third hub-section">
  <p>Petition</p>
</div>

<div class="usa-grid usa-width-one-third hub-section">
  <p>Institutions</p>
</div>

app/views/users/new.erb
<%= erb :'_errors' %>
<h1>Register Below</h1>

<form action="/users" method="POST">
  <label>User Name:</label>
  <input type="text" name="user[username]">
  <br><br>
  <label>Email:</label>
  <input type="text" name="user[email]">
  <br><br>
  <label>Password:</label>
  <input type="password" name="user[password]">
  <br><br>
  <input type="submit" value="Register">
</form>

app/views/users/new.html.erb
<body class="auth-bg">

<div id="registration-container">
  <span class="usa-header auth-header">Sign Up</span>
  <p>This site is currently in early stages of development but
  its goal is to dramatically improve the citizen role in governance.  For more previews and an explanation of the plans for this project check out <%= link_to "digiciti.org.", "https://digiciti.org/" %></p>

  <p>Sign up below to stay updated with improvements in the project and to try out some of the existing features.</p>

  <%= flash[:error] %>
  <%= form_for :user, url: '/users' do |f| %>

    User Name: <%= f.text_field :username, class: 'auth-inputs' %><br>
    Email: <%= f.text_field :email, class: 'auth-inputs' %><br>
    Password: <%= f.password_field :password, class: 'auth-inputs' %><br>
    Password Confirmation: <%= f.password_field :password_confirmation, class: 'auth-inputs' %><br>
    <%= f.submit "Register" %>

  <% end %>
</div>

app/views/users/search_results.html.erb
<!-- This will need to utilize search result pagination and ordering/filtering -->
<!-- Add feature for more advanced search parameters such as geographic location -->

<div class="usa-grid usa-width-one-half" id="search-results-cont">
  <p>Search results for "<%= @query %>":</p>
  <hr>
  <div id="search-c-members-cont">
    <p>Found members of congress:</p>
    <% if @congress_members.count > 0 %>
      <% @congress_members.each do |member| %>
        <div class="search-c-member-details-cont">
          <%= image_tag "https://theunitedstates.io/images/congress/225x275/#{member["member_id"]}.jpg", alt: "Image N/A", class: "search-c-member-img" %>
          <p>
            <%= link_to "#{member["first_name"]} #{member["last_name"]}",
            congress_member_path(member_id: member["member_id"],
            id: signed_in? ? current_user.id : 1) %>
            - <%= "#{member["roles"][0]["chamber"]}" %>
            - <%= "#{member["roles"][0]["title"]}" %>
            - <%= "#{member["current_party"]}" %>
            - <%= "#{member["roles"][0]["state"]}" %>
          </p>
        </div>
      <% end %>
    <% else %>
      <p>No members of congress were found by that name.</p>
    <% end %>
  </div>

  <div id="search-users-results-cont">
    <p>Found digital citizens:</p>
    <% if @users.count > 0 %>
      <% @users.each do |user| %>
        <div class="search-user-result-cont">
          <%= link_to user_path(user.id) do %>
            <%= image_tag user.avatar.url(:thumb), class: "searched-user-avatar" %>
          <% end %>
          <%= link_to user.username, "/users/#{user.id}" %>
        </div>
      <% end %>
    <% else %>
      <p>There are no digital citizens by that name.</p>
    <% end %>
  </div>
</div>

app/views/users/show.erb
<h3>Welcome <%= @user.username %></h3>
<% count = 0 %>
<% @user.responses.each do |response| %>
  <% count += 1 %>
  <p>Quiz <%= count %> had a result of: <%= response.quiz_result %></p>
<% end %>

app/views/users/show.html.erb
<div class="usa-grid usa-width-one-half" id="profile-page-main-cont">
  <div id="profile-info-cont">
    <span id="profile-username-header"><%= @user.username %></span>
    <div id="profile-badge-display">
      <%= image_tag 'law.png', class: "badge-icon" %>
      <%= image_tag 'learning.png', class: "badge-icon" %>
      <%= image_tag 'lecture-1.png', class: "badge-icon" %>
      <%= image_tag 'writing.png', class: "badge-icon" %>
      <%= image_tag 'lecture.png', class: "badge-icon" %>
      <%= image_tag 'notebook.png', class: "badge-icon" %>
    </div>
    <br>
    <%= image_tag @user.avatar.url(:medium), id: "profile-photo-cont" %>
    <div class="profile-basic-info">
      <%= @user.city %><br>
      <%= @user.state %><br>
      <%= @user.country %><br>
      <%= @user.ideology %><br>
      <%= @user.party %><br><br>
      <% if signed_in? && @user.id == current_user.id %>
        <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
      <% end %>
    </div>
    <div class="profile-basic-info">
      <%= "Issues:" %><br>
      <%= "Verified:" %><br>
      <%= "Digiciti Since: #{@user.created_at.strftime('%m/%d/%y')}" %><br>
      <%= "Organizations: " %><br>
      <%= "Profile Type: " %><br><br>
    </div>
    <% if signed_in? && @user.id != current_user.id && !friend?(@user.id) %>
    <%= button_to "Add Contact", friendships_path(add_id: @user.id), method: :post %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% end %>
  </div>

    <% if signed_in? && @user.id == current_user.id %>
      <%= link_to 'New Post', new_entry_path, remote: true, id: "new-post-btn", class: "usa-button" %>
    <% end %>
    <div id="profile-post-form-cont">
      <%= render '/entries/profile_post_form' %>
    </div>

  <div id="profile-posts-cont">
    <% @posts.each do |post| %>
      <%= render '/entries/show', post: post %>
    <% end %>
  </div>
</div>

app/views/users/welcome.html.erb
<!-- Sample page template from US Design Standards -->

<div class="usa-overlay"></div>
<main id="main-content">
  <section class="usa-hero">
    <div class="usa-grid">
      <div class="usa-hero-callout usa-section-dark">
        <h2><span class="usa-hero-callout-alt">Hero callout:</span> Call attention to a current priority</h2>
        <a class="usa-hero-link" href="#">Link to more about that priority</a>
        <a class="usa-button usa-button-big usa-button-secondary" href="#">Learn about what we do</a>
      </div>
    </div>
  </section>
  <section class="usa-grid usa-section">
    <div class="usa-width-one-third">
      <h2>A tagline highlights your approach.</h2>
    </div>
    <div class="usa-width-two-thirds">
      <p>The tagline should inspire confidence and interest, focusing on the value that your overall approach offers to your audience. Use a heading typeface and keep your tagline to just a few words, and don’t confuse or mystify.</p>
      <p>Use the right side of the grid to explain the tagline a bit more. What are your goals? How do you do your work? Write in the present tense, and stay brief here. People who are interested can find details on internal pages.</p>
    </div>
  </section>
  <section class="usa-section usa-section-dark usa-graphic_list">
    <div class="usa-grid usa-graphic_list-row">
      <div class="usa-width-one-half usa-media_block">
        <img class="usa-media_block-img"  src="/assets/img/circle-124.png" alt="Alt text">
        <div class="usa-media_block-body">
          <h3>Graphic headings can vary.</h3>
          <p>Graphic headings can be used a few different ways, depending on what your landing page is for. Highlight your values, specific program areas, or results.</p>
        </div>
      </div>
      <div class="usa-width-one-half usa-media_block">
        <img class="usa-media_block-img"  src="/assets/img/circle-124.png" alt="Alt text">
        <div class="usa-media_block-body">
          <h3>Stick to 6 or fewer words.</h3>
          <p>Keep body text to about 30. They can be shorter, but try to be somewhat balanced across all four. It creates a clean appearance with good spacing.</p>
        </div>
      </div>
    </div>
    <div class="usa-grid usa-graphic_list-row">
      <div class="usa-width-one-half usa-media_block">
        <img class="usa-media_block-img"  src="/assets/img/circle-124.png" alt="Alt text">
        <div class="usa-media_block-body">
          <h3>Never highlight anything without a goal.</h3>
          <p>For anything you want to highlight here, understand what your users know now, and what activity or impression you want from them after they see it.</p>
        </div>
      </div>
      <div class="usa-width-one-half usa-media_block">
        <img class="usa-media_block-img"  src="/assets/img/circle-124.png" alt="Alt text">
        <div class="usa-media_block-body">
          <h3>Could also have 2 or 6.</h3>
          <p>In addition to your goal, find out your users’ goals. What do they want to know or do that supports your mission? Use these headings to show those.</p>
        </div>
      </div>
    </div>
  </section>
  <section class="usa-section">
    <div class="usa-grid">
      <h2>Section heading</h2>
      <p class="usa-font-lead">Everything up to this point should help people understand your agency or project: who you are, your goal or mission, and how you approach it. Use this section to encourage them to act. Describe why they should get in touch here, and use an active verb on the button below. “Get in touch,” “Learn more,” and so on.</p>
      <a class="usa-button usa-button-big" href="#">Call to action</a>
    </div>
  </section>
</main>