config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :index, :create, :show, :edit, :update, :destroy]
  get '/users/hub/:id', to: 'users#hub', as: :hub
  get '/users/welcome', to: 'users#welcome', as: :welcome #needs fix, routes to show

  resources :friendships, only: [:create, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :quiz_responses, only: [:new, :create, :show]
  resources :congress_members, only: [:index, :show]
  resources :entries, only: [:new, :create, :edit, :update, :destroy]
  resources :comments, only: [:new, :create, :edit, :update, :destroy]

  root 'users#new'
end

app/views/layouts/_nav_bar.erb
<div id="nav-container" class="nav-gradient">
  <% if signed_in? %>
    <%= link_to image_tag("digiciti_logo.png", id: 'nav-logo'), "/users/hub/#{current_user.id}", onclick: "this.blur();" %>
    <%= link_to "Digital Citizen", "/users/hub/#{current_user.id}", id: "nav-title", onclick: "this.blur();" %>
  <% else %>
    <%= image_tag "digiciti_logo.png", id: 'nav-logo' %>
    <span id="nav-title">Digital Citizen</span>
  <% end %>
  <%= form_tag users_path, id: "nav-search-form", method: :get do %>
    <%= text_field_tag :q, nil, placeholder: "find digital citizens or politicians...", id: "nav-search-field" %>
    <%= image_submit_tag("search-icon-md.png", id: "nav-search-submit", class: "usa-button-unstyled") %>
  <% end %>
  <div id="navbar">
    <!-- should refactor all to link_to -->
    <% if current_user %>
      <div id="nav-logged-user"><%= current_user.username %> &nbsp&nbsp </div> |
      <%= link_to "Profile", user_path(current_user.id), class: "nav-item", onclick: "this.blur();" %>
      <%= link_to "Logout", '/sessions/:id', method: "delete", class: "nav-item", onclick: "this.blur();" %>
      <%= link_to "Hub", "/users/hub/#{current_user.id}", class: "nav-item", onclick: "this.blur();" %>
    <% else %>
      <%= link_to "Sign Up", '/users/new', class: "nav-item", onclick: "this.blur();" %>
      <%= link_to "Login", new_session_path, class: "nav-item", onclick: "this.blur();" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigiCiti</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav_bar" %>
    <%= yield %>
  </body>
</html>